# Bag of words technique

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({"text":["likhith like sports",
                         "I watch sports",
                         "likhith plays sports",
                          "i love sports"],"output":[1,1,0,0]})

df

text  output
0   likhith like sports       1
1        I watch sports       1
2  likhith plays sports       0
3         i love sports       0

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [4]:
bow = cv.fit_transform(df['text'])

In [5]:
#vocabulary
print(cv.vocabulary_)

{'likhith': 1, 'like': 0, 'sports': 4, 'watch': 5, 'plays': 3, 'love': 2}


In [6]:
bow.toarray()

array([[1, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 1],
       [0, 1, 0, 1, 1, 0],
       [0, 0, 1, 0, 1, 0]])

In [7]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[1 1 0 0 1 0]]
[[0 0 0 0 1 1]]
[[0 1 0 1 1 0]]


In [9]:
# new
cv.transform(['I watch sports']).toarray()

array([[0, 0, 0, 0, 1, 1]])

In [10]:
X = bow.toarray()
y = df['output']

#  N-grams

In [11]:
df = pd.DataFrame({"text":["likhith like sports",
                         "I watch sports",
                         "likhith plays sports",
                          "i love sports"],"output":[1,1,0,0]})

df

text  output
0   likhith like sports       1
1        I watch sports       1
2  likhith plays sports       0
3         i love sports       0

In [12]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [13]:
bow = cv.fit_transform(df['text'])

In [14]:
print(cv.vocabulary_)

{'likhith like': 1, 'like sports': 0, 'watch sports': 5, 'likhith plays': 2, 'plays sports': 4, 'love sports': 3}


In [15]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[1 1 0 0 0 0]]
[[0 0 0 0 0 1]]
[[0 0 1 0 1 0]]


In [16]:
#Ti gram
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [17]:
bow = cv.fit_transform(df['text'])

In [18]:
print(cv.vocabulary_)

{'likhith like sports': 0, 'likhith plays sports': 1}


In [19]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[1 0]]
[[0 0]]
[[0 1]]


# TF-IDF (Term frequency- Inverse document frequency)

In [20]:
df = pd.DataFrame({"text":["likhith like sports",
                         "I watch sports",
                         "likhith plays sports",
                          "i love sports"],"output":[1,1,0,0]})

df

text  output
0   likhith like sports       1
1        I watch sports       1
2  likhith plays sports       0
3         i love sports       0

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [22]:
arr = tfid.fit_transform(df['text']).toarray()

In [23]:
arr

array([[0.72664149, 0.5728925 , 0.        , 0.        , 0.37919167,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.46263733,
        0.88654763],
       [0.        , 0.5728925 , 0.        , 0.72664149, 0.37919167,
        0.        ],
       [0.        , 0.        , 0.88654763, 0.        , 0.46263733,
        0.        ]])

In [24]:
print(tfid.idf_)

[1.91629073 1.51082562 1.91629073 1.91629073 1.         1.91629073]
